- platform: workday
  country: 'NO'

- platform: template
  sensors:
    balcony_door_sensor_2:
      device_class: opening
      friendly_name: "Balcony door"
      value_template: "{{ states('sensor.balcony_door_sensor_access_control') | int == 22 }}"
  
    washing_machine_activity:
      friendly_name: "Washing machine running state"
      delay_on:
        seconds: 15
      delay_off:
        minutes: 4
      value_template: "{{ states('sensor.washing_machine_power') | float > 45 }}"
      icon_template: mdi:washing-machine
  
    dryer_activity:
      friendly_name: "Dryer running state"
      delay_on:
        seconds: 10
      delay_off:
        minutes: 1
      value_template: "{{ states('sensor.dryer_power') | float > 45 }}"
      icon_template: mdi:tumble-dryer
    
    dishwasher_activity:
      friendly_name: "Dishwasher running state"
      delay_on:
        seconds: 10
      delay_off:
        minutes: 1
      value_template: "{{ states('sensor.dishwasher_power') | float > 2 }}"
      icon_template: mdi:dishwasher
    
    low_priced_electricity:
      friendly_name: "EL price below average"
      value_template: "{{ states('sensor.electricity_price_holmsens_vei_29b') | float() < state_attr('sensor.electricity_price_holmsens_vei_29b', 'avg_price') | float }}"

    doorbell_state:
      friendly_name: "Doorbell"
      entity_id: binary_sensor.doorbell
      device_class: "occupancy"
      value_template: "{{ is_state('binary_sensor.doorbell', 'on') }}"
      delay_off:
        seconds: 5

    sleep_state:
      friendly_name: "Sleep State"
      entity_id: input_boolean.sleep_state_tor, input_boolean.sleep_state_lande, input_boolean.sleep_state_ingrid, input_boolean.sleep_state_guests, binary_sensor.morning, binary_sensor.day, binary_sensor.evening, binary_sensor.night
      value_template: "{{ (not is_state('device_tracker.google_maps_117621586906275495071', 'home') or is_state('input_boolean.sleep_state_tor', 'on')) and (not is_state('device_tracker.google_maps_106703534047375134126', 'home') or is_state('input_boolean.sleep_state_lande', 'on')) and (not is_state('device_tracker.ingrid_phone', 'home') or is_state('input_boolean.sleep_state_ingrid', 'on')) and (is_state('input_boolean.guests_present', 'on') == is_state('input_boolean.sleep_state_guests', 'on')) and (is_state('binary_sensor.night', 'on') or is_state('binary_sensor.evening', 'on')) }}"

- platform: trend
  sensors:
    water_heater:
      entity_id: sensor.water_heater
      device_class: heat
      friendly_name: "Water heater"
      min_gradient: 0.0016
      max_samples: 5
      sample_duration: 10

- platform: tod
  name: Morning
  after: '06:00'
  before: '09:00'
  
- platform: tod
  name: Day
  after: '09:00'
  before: '19:30'
  
- platform: tod
  name: Evening
  after: '19:30'
  before: '01:00'
  
- platform: tod
  name: Night
  after: '01:00'
  before: '06:00'
  

