- platform: workday
  country: 'NO'
- platform: template
  sensors:
    balcony_door_sensor_2:
      device_class: opening
      friendly_name: "Balcony door"
      value_template: "{{ states('sensor.balcony_door_sensor_access_control') | int == 22 }}"
  
    washing_machine_activity:
      friendly_name: "Washing machine running state"
      delay_on:
        seconds: 15
      delay_off:
        minutes: 4
      value_template: "{{ states('sensor.washing_machine_power') | float > 45 }}"
  
    dryer_activity:
      friendly_name: "Dryer running state"
      delay_on:
        seconds: 10
      delay_off:
        minutes: 1
      value_template: "{{ states('sensor.dryer_power') | float > 45 }}"
    
    low_priced_electricity:
      friendly_name: "EL price below average"
      value_template: "{{ states('sensor.electricity_price_holmsens_vei_29b') | float() < state_attr('sensor.electricity_price_holmsens_vei_29b', 'avg_price') | float }}"

    doorbell_state:
      friendly_name: "Doorbell"
      entity_id: binary_sensor.doorbell
      device_class: "occupancy"
      value_template: "{{ is_state('binary_sensor.doorbell', 'on') }}"
      delay_off:
        seconds: 15

- platform: trend
  sensors:
    water_heater:
      entity_id: sensor.water_heater
      device_class: heat
      friendly_name: "Water heater"
      min_gradient: 0.0016
      max_samples: 5
      sample_duration: 10
