- platform: workday
  country: 'NO'
- platform: template
  sensors:
    balcony_door_sensor_2:
      device_class: opening
      friendly_name: "Balcony door"
      value_template: "{{ states.sensor.balcony_door_sensor_access_control.state == '22' }}"
  
    washing_machine_activity:
      friendly_name: "Washing machine running state"
      delay_on:
        seconds: 15
      delay_off:
        minutes: 4
      value_template: "{{ states.sensor.washing_machine_power.state | float > 45 }}"
  
    dryer_activity:
      friendly_name: "Dryer running state"
      delay_on:
        seconds: 10
      delay_off:
        minutes: 1
      value_template: "{{ states.sensor.dryer_power.state | float > 45 }}"
    
    low_priced_electricity:
      friendly_name: "EL price below average"
      value_template: "{{ states.sensor.elspot_kwh.state|float() < states.sensor.elspot_kwh.attributes.Average|float() }}"
