homeassistant:
  # Customization file
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
   - type: trusted_networks
     trusted_networks:
        - 127.0.0.1

auth:
# Discover some devices automatically
#discovery:
#zeroconf:
#ssdp:

system_health:

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes/

config:
person:
map:

recorder:
  db_url: !secret mysql_connection

http:
  ip_ban_enabled: true
  ssl_certificate: /config/ssl/fullchain.pem
  ssl_key: /config/ssl/privkey.pem
  base_url: !secret http_base_url

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  autoheal: false

prometheus:
  component_config_glob:
    sensor.*_volume:
      override_metric: water_volume
    sensor.*_area:
      override_metric: room_area

device_tracker:
#  - platform: unifi
#    host: !secret unifi_host
#    verify_ssl: False
#    username: !secret unifi_username
#    password: !secret unifi_password

  - platform: google_maps
    username: !secret google_maps_username

#  - platform: icloud
#    username: !secret icloud_username
#    password: !secret icloud_password

mobile_app:

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 100
    icon: mdi:home-modern
  - name: School
    latitude: !secret school_latitude
    longitude: !secret school_longitude
    radius: 150
    icon: mdi:school
  - name: Dancing
    latitude: !secret dancing_latitude
    longitude: !secret dancing_longitude
    radius: 100
    icon: mdi:school
  - name: Tor Magnus Work
    latitude: !secret tor_magnus_work_latitude
    longitude: !secret tor_magnus_work_longitude
    radius: 120
    icon: mdi:worker
  - name: Lande Work
    latitude: !secret lande_work_latitude
    longitude: !secret lande_work_longitude
    radius: 120
    icon: mdi:worker
  - name: Cabin
    latitude: !secret cabin_latitude
    longitude: !secret cabin_longitude
    radius: 1000
    icon: mdi:image-filter-hdr

proximity:
  vacation:
    zone: home
    devices: 
      - device_tracker.google_maps_117621586906275495071
      - device_tracker.google_maps_106703534047375134126
      - device_tracker.ingrid_phone
    tolerance: 50000
    unit_of_measurement: m
  tmc_home:
    zone: home
    devices:
      - device_tracker.google_maps_117621586906275495071
    tolerance: 100
    unit_of_measurement: m
  lande_home:
    zone: home
    devices:
      - device_tracker.google_maps_106703534047375134126
    tolerance: 100
    unit_of_measurement: m
  ingrid_home:
    zone: home
    devices:
      - device_tracker.ingrid_phone
    tolerance: 100
    unit_of_measurement: m

remote:
  - platform: xiaomi_miio
    name: "TV Room remote"
    host: !secret xiaomi_ir_ip
    token: !secret xiaomi_ir_token
    hidden: true
    commands:
      power:
        command:
          - 'pronto:0000 006d 0022 0003 00a9 00a8 0015 003f 0015 003f 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003f 0015 003f 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0015 0015 003f 0015 003f 0015 003f 0015 003f 0015 003f 0015 003f 0015 0702 00a9 00a8 0015 0015 0015 0e6e'
      hdmi_1:
        command:
          - 'pronto:0000 006D 0000 0022 00AB 00AB 0015 003F 0015 003F 0015 003F 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003F 0015 003F 0015 003F 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003F 0015 0015 0015 0015 0015 003F 0015 0015 0015 003F 0015 003F 0015 003F 0015 0015 0015 003F 0015 003F 0015 0015 0015 003F 0015 0015 0015 0015 0015 0015 0015 071C'
      hdmi_2:
        command:
          - 'pronto:0000 006D 0000 0022 00AC 00AB 0015 0041 0015 0041 0015 0041 0015 0016 0015 0016 0015 0016 0015 0016 0015 0016 0015 0041 0015 0041 0015 0041 0015 0016 0015 0016 0015 0016 0015 0016 0015 0016 0015 0016 0015 0041 0015 0041 0015 0041 0015 0041 0015 0041 0015 0016 0015 0041 0015 0041 0015 0016 0015 0016 0015 0016 0015 0016 0015 0016 0015 0041 0015 0016 0015 0689'
      hdmi_3:
        command:
          - 'pronto:0000 006D 0000 0022 00AC 00AC 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0040 0015 0015 0015 0040 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0689'
      hdmi_4:
        command:
          - 'pronto:0000 006D 0000 0022 00AC 00AB 0015 0041 0015 0041 0015 0041 0015 0016 0015 0016 0015 0016 0015 0016 0015 0016 0015 0041 0015 0041 0015 0041 0015 0016 0015 0016 0015 0016 0015 0016 0015 0016 0015 0041 0015 0016 0015 0041 0015 0016 0015 0016 0015 0016 0015 0041 0015 0041 0015 0016 0015 0041 0015 0016 0015 0041 0015 0041 0015 0041 0015 0016 0015 0016 0015 0689'
      volume_up:
        command:
          - 'pronto:0000 006d 0022 0003 00a9 00a8 0015 003f 0015 003f 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003f 0015 003f 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003f 0015 003f 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003f 0015 003f 0015 003f 0015 003f 0015 003f 0015 0702 00a9 00a8 0015 0015 0015 0e6e'
      volume_down:
        command:
          - 'pronto:0000 006d 0022 0003 00a9 00a8 0015 003f 0015 003f 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003f 0015 003f 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003f 0015 003f 0015 0015 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003f 0015 0015 0015 003f 0015 003f 0015 003f 0015 003f 0015 0702 00a9 00a8 0015 0015 0015 0e6e'
      mute:
        command:
          - 'pronto:0000 006c 0022 0003 00ab 00aa 0015 003f 0015 003f 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003f 0015 003f 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003f 0015 0015 0015 003f 0015 003f 0015 0015 0015 0015 0015 0015 0015 003f 0015 0015 0015 003f 0015 0015 0015 0015 0015 003f 0015 003f 0015 003f 0015 0714 00ab 00aa 0015 0015 0015 0e91'


camera:
  - platform: ffmpeg
    name: Hallway Camera
    input: !secret foscam_ffmpeg 
  - platform: generic
    name:  Hallway Camera generic
    still_image_url: !secret foscam_rtsp
    stream_source: !secret foscam_rtsp

  - platform: ffmpeg
    name: Side lawn
    input: !secret nvr_front_south_ffmpeg
  - platform: generic
    name: Side lawn generic
    still_image_url: !secret nvr_front_south_rtsp
    stream_source: !secret nvr_front_south_rtsp

  - platform: ffmpeg
    name: Front door
    input: !secret nvr_front_stairs_ffmpeg
  - platform: generic
    name: Front door generic
    still_image_url: !secret nvr_front_stairs_rtsp
    stream_source: !secret nvr_front_stairs_rtsp

  - platform: ffmpeg
    name: Front lawn
    input: !secret nvr_front_east_ffmpeg
  - platform: generic
    name: Front lawn generic
    still_image_url: !secret nvr_front_east_rtsp
    stream_source: !secret nvr_front_east_rtsp

  - platform: ffmpeg
    name: Car parking
    input: !secret nvr_front_north_ffmpeg
  - platform: generic
    name: Car parking generic
    still_image_url: !secret nvr_front_north_rtsp
    stream_source: !secret nvr_front_north_rtsp

  - platform: ffmpeg
    name: Tool shed
    input: !secret nvr_rear_south_ffmpeg
  - platform: generic
    name: Tool shed generic
    still_image_url: !secret nvr_rear_south_rtsp
    stream_source: !secret nvr_rear_south_rtsp

  - platform: ffmpeg
    name: Back garden
    input: !secret nvr_rear_north_ffmpeg
  - platform: generic
    name: Back garden generic
    still_image_url: !secret nvr_rear_north_rtsp
    stream_source: !secret nvr_rear_north_rtsp

stream:

# Enables support for tracking state changes over time
history:

logger:
  default: warning
  logs:
    homeassistant.components.automation: info
    homeassistant.components.switch: warning
    homeassistant.components.light: info 
    homeassistant.components.zwave: info
    homeassistant.components.lock: info
    homeassistant.components.python_script: info
    homeassistant.components.http.ban: warning
    homeassistant.components.prometheus: error
    homeassistant.components.netatmo: error

# View all events in a logbook
logbook:
  exclude:
    domains:
      - sensor

# Track the sun
sun:

tibber:
  access_token: !secret tibber_token

cast:
  media_player:
    # Google Home
    - host: 192.168.0.123
    - host: 192.168.0.124
    - host: 192.168.0.125
    - host: 192.168.0.126
    # Google Chromecast
    - host: 192.168.0.201
    - host: 192.168.0.202
    - host: 192.168.0.203
    - host: 192.168.0.204

sonos:
  media_player:
    hosts:
      - 192.168.0.211
      - 192.168.0.212

media_player:
  - platform: spotify
    name: Spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_secret
    aliases:
      c9eda3351755203eb884ee413f2552d58b115aa4: "TMC phone"

climate:
  - platform: mill
    username: !secret mill_username
    password: !secret mill_password

tesla:
  username: !secret tesla_username
  password: !secret tesla_password
  scan_interval: 600

vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_roborock_ip
    token: !secret xiaomi_roborock_token

verisure:
  username: !secret verisure_username
  password: !secret verisure_password
  smartplugs: 0
  locks: 0
  thermometers: 0
  mouse: 0
  door_window: 0


# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    time_memory: 3600

input_select:
  home_state:
    name: Home State
    icon: mdi:home-circle
    options:
      - Home
      - Away
      - Vacation

  vacuum_area:
    name: Choose an area to clean
    options:
      - Select Area
      - island
      - table
      - hallway


input_datetime:
  alarm_time_tor:
    name: Alarm Time
    has_date: false
    has_time: true
  alarm_time_lande:
    name: Alarm Time
    has_date: false
    has_time: true
  alarm_time_ingrid:
    name: Alarm Time
    has_date: false
    has_time: true


notify:
  - name: mail
    platform: smtp
    sender: !secret notify_mail_sender
    sender_name: My Home Assistant
    recipient: !secret notify_mail_recipient
    server: !secret notify_mail_server
    port: 25
  - name: html5
    platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
  - name: hangouts
    platform: hangouts
    default_conversations:
      - id: "UgyQRp0_hCwqYHGaPO54AaABAagBo4W8AQ"


google_assistant:
  project_id: api-project-511361644410
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - light
    - climate
  entity_config:
    input_boolean.sleep_state_tor:
      name: tor magnus sleeping
      expose: true
      room: Master bedroom
    input_boolean.sleep_state_lande:
      name: lande sleeping
      expose: true
      room: Master bedroom
    input_boolean.dinner_time:
      name: dinner time
      expose: true
    input_boolean.sleep_state_ingrid:
      name: ingrid sleeping
      expose: true
      room: Ingrid bedroom
    input_boolean.red_alert:
      name: Red Alert
      expose: true
      room: Dining room
    input_boolean.fireplace:
      name: Fireplace
      expose: true
      room: TV room
    light.fibaro_system_fgd212_dimmer_2_level:
      expose: false
    light.fibaro_system_fgd212_dimmer_2_level_2:
      expose: false
    light.fibaro_system_fgd212_dimmer_2_level_3:
      expose: false
    light.fibaro_system_fgd212_dimmer_2_level_4:
      expose: false
    light.fibaro_system_fgd212_dimmer_2_level_5:
      expose: false
    light.fibaro_system_fgd212_dimmer_2_level_6:
      expose: false
    light.fibaro_system_fgd212_dimmer_2_level_7:
      expose: false
    light.fibaro_system_fgd212_dimmer_2_level_8:
      expose: false
    light.fibaro_system_fgd212_dimmer_2_level_9:
      expose: false
    light.fibaro_system_fgd212_dimmer_2_level_10:
      expose: false
    light.fibaro_system_fgd212_dimmer_2_level_13:
      expose: false
    light.fibaro_system_fgd212_dimmer_2_level_12:
      expose: false
    light.fibaro_system_fgrgbwm441_rgbw_controller_level_2:
      expose: false
    light.fibaro_system_fgrgbwm441_rgbw_controller_level_3:
      expose: false
    light.fibaro_system_fgrgbwm441_rgbw_controller_level_4:
      expose: false
    light.fibaro_system_fgrgbwm441_rgbw_controller_level_5:
      expose: false
    light.fibaro_system_fgrgbwm441_rgbw_controller_level_6:
      expose: false
    light.house_ventilation_dimmer_level:
      expose: false
    light.bedroom_tv_backlight_level_2:
      expose: false
    light.bedroom_tv_backlight_level_3:
      expose: false
    light.bedroom_tv_backlight_level_4:
      expose: false
    light.bedroom_tv_backlight_level_5:
      expose: false
    light.bedroom_tv_backlight_level_6:
      expose: false
    light.family_bathroom_dimmer_level_2:
      expose: false
    light.laundry_dimmer_level_2:
      expose: false
    light.master_bathroom_dimmer_level_2:
      expose: false
    light.house_ventilation_dimmer_level_2:
      expose: false
    light.downstairs_hallway_pendant_level_2:
      expose: false
    light.dining_room_rail_1_level_2:
      expose: false
    light.dining_room_rail_2_level_2:
      expose: false
    light.dining_room_rail_3_level_2:
      expose: false
    light.tv_area_level_2:
      expose: false
    light.sofa_area_level_2:
      expose: false
    light.hallway_area_level_2:
      expose: false
    light.entrance_hallway_ceiling_lights_level_2:
      expose: false
    light.changing_room_ceiling_light_level_2:
      expose: false
    light.ingrid_bedroom_ceiling_light_level_2:
      expose: false
    light.ingrid_bedroom_bed_light_level_2:
      expose: false
    light.ingrid_bedroom_bed_light_level_3:
      expose: false
    light.ingrid_bedroom_bed_light_level_4:
      expose: false
    light.ingrid_bedroom_bed_light_level_5:
      expose: false
    light.ingrid_bedroom_bed_light_level_6:
      expose: false
    light.kitchen_bench_ceiling_lights_level_2:
      expose: false
    light.kitchen_table_ceiling_lamp_level_2:
      expose: false
    light.hallway_toilet_ceiling_dimmer_level_2:
      expose: false
    light.entrance_hallway_ceiling_lights_level_2:
      expose: false
    light.ingrid_bedroom_bed_light_blue_level:
      expose: false
    light.ingrid_bedroom_bed_light_green_level:
      expose: false
    light.ingrid_bedroom_bed_light_level_2:
      expose: false
    light.ingrid_bedroom_bed_light_red_level:
      expose: false
    light.ingrid_bedroom_bed_light_white_level:
      expose: false
    light.nook_mood_blue_level:
      expose: false
    light.nook_mood_green_level:
      expose: false
    light.nook_mood_level_2:
      expose: false
    light.nook_mood_red_level:
      expose: false
    light.nook_mood_white_level:
      expose: false    

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password
  discovery: true

octoprint:
  host: !secret octoprint_host
  api_key: !secret octoprint_key
  name: "Prusa i3 MK2S"
  bed: true
  number_of_tools: 1

utility_meter:
  water_yearly:
    source: sensor.water_consumption_volume
    cycle: yearly
    tariffs:
      - fixed
  water_monthly:
    source: sensor.water_consumption_volume
    cycle: monthly
    tariffs:
      - fixed
  water_daily:
    source: sensor.water_consumption_volume
    cycle: daily
    tariffs:
      - fixed
  electricity_yearly:
    source: sensor.electricity_meter_consumption
    cycle: yearly
    tariffs:
      - fixed
  electricity_monthly:
    source: sensor.electricity_meter_consumption
    cycle: monthly
    tariffs:
      - fixed
  electricity_daily:
    source: sensor.electricity_meter_consumption
    cycle: daily
    tariffs:
      - fixed
  electricity_cost_yearly:
    source: sensor.electricity_meter_accmulated_cost
    cycle: yearly
    tariffs:
      - fixed
  electricity_cost_monthly:
    source: sensor.electricity_meter_accmulated_cost
    cycle: monthly
    tariffs:
      - fixed
  electricity_cost_daily:
    source: sensor.electricity_meter_accmulated_cost
    cycle: daily
    tariffs:
      - fixed

input_boolean: !include input_boolean.yaml
switch: !include switch.yaml
group: !include groups.yaml
binary_sensor: !include binary-sensor.yaml
sensor: !include sensor.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
#alert: !include alerts.yaml
intent_script: !include intent_scripts.yaml
hangouts: !include hangout_intents.yaml
fan: !include fans.yaml
light: !include light.yaml
