homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude_short
  longitude: !secret home_longitude_short
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 154
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo
  # Customization file
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password

auth:

# Show links to resources in log and frontend
# introduction:

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes/

config:

map:

recorder:
  db_url: !secret mysql_connection

http:
  api_password: !secret http_api_password
  #base_url: !secret http_base_url

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  autoheal: false

prometheus:

device_tracker:
  - platform: unifi
    host: !secret unifi_host
    verify_ssl: False
    username: !secret unifi_username
    password: !secret unifi_password

  - platform: google_maps
    username: !secret google_maps_username
    password: !secret google_maps_password

# Discover some devices automatically
#discovery:

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 30
    icon: mdi:home-modern
  - name: School
    latitude: !secret school_latitude
    longitude: !secret school_longitude
    radius: 70
    icon: mdi:school
  - name: Tor Magnus Work
    latitude: !secret tor_magnus_work_latitude
    longitude: !secret tor_magnus_work_longitude
    radius: 70
    icon: mdi:worker
  - name: Lande Work
    latitude: !secret lande_work_latitude
    longitude: !secret lande_work_longitude
    radius: 70
    icon: mdi:worker
  - name: Cabin
    latitude: !secret cabin_latitude
    longitude: !secret cabin_longitude
    radius: 100
    icon: mdi:image-filter-hdr

proximity:
  tmc_home:
    zone: home
    devices:
      - device_tracker.google_maps_117621586906275495071
    tolerance: 100
    unit_of_measurement: m
  lande_home:
    devices:
      - device_tracker.google_maps_106703534047375134126
    tolerance: 100
    unit_of_measurement: m

camera:
  - platform: ffmpeg
    name: Hallway Camera
    input: !secret foscam_url 
  - platform: ffmpeg
    name: Test camera
    input: -rtsp_transport tcp -i rtsp://192.168.0.36:554/user=admin&password=&channel=7&stream=0.sdp?real_stream--rtp-caching=100
  - platform: ffmpeg
    name: Parking camera
    input: -rtsp_transport tcp -i rtsp://192.168.0.36:554/user=admin&password=&channel=1&stream=0.sdp?real_stream--rtp-caching=100
  - platform: ffmpeg
    name: Entrance camera
    input: -rtsp_transport tcp -i rtsp://192.168.0.36:554/user=admin&password=&channel=2&stream=0.sdp?real_stream--rtp-caching=100
  - platform: ffmpeg
    name: Garden camera
    input: -rtsp_transport tcp -i rtsp://192.168.0.36:554/user=admin&password=&channel=3&stream=0.sdp?real_stream--rtp-caching=100
#  - platform: generic
#    name: Hallway Camera
#    still_image_url: !secret camera_still_image_url

# Enables support for tracking state changes over time
history:

logger:
  default: warning
  logs:
    homeassistant.components.automation: info
    homeassistant.components.switch: warning
    homeassistant.components.light: info 
    homeassistant.components.zwave: info
    homeassistant.components.lock: info

# View all events in a logbook
logbook:

# Track the sun
sun:

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_control_panel_code
    pending_time: 30
    armed_home:
      pending_time: 0
    triggered:
      pending_time: 30
    trigger_time: 4 

cast:
  media_player:
  - host: 192.168.0.201
  - host: 192.168.0.202
  - host: 192.168.0.203
  - host: 192.168.0.204

sonos:
  media_player:
    hosts:
      - 192.168.0.211
      - 192.168.0.212

tesla:
  username: !secret tesla_username
  password: !secret tesla_password
  scan_interval: 600

verisure:
  username: !secret verisure_username
  password: !secret verisure_password
  smartplugs: 0
  locks: 0
  thermometers: 0
  mouse: 0
  door_window: 0


# Text to speech
tts:
  - platform: google

input_select:
  time_of_day:
    name: Time of Day
    icon: mdi:chart-timeline
    options:
      - Night
      - Morning
      - Day
      - Evening
  home_state:
    name: Home State
    icon: mdi:home-circle
    options:
      - Home
      - Away

input_boolean:
  sleep_state_tor:
    name: Sleeping
    icon: mdi:sleep
  alarm_override_tor:
    name: Alarm Disabled
    icon: mdi:cancel
  alarm_workday_tor:
    name: Workdays Only
    icon: mdi:calendar-check

  sleep_state_lande:
    name: Sleeping
    icon: mdi:sleep
  alarm_override_lande:
    name: Alarm Disabled
    icon: mdi:cancel
  alarm_workday_lande:
    name: Workdays Only
    icon: mdi:calendar-check

  sleep_state_ingrid:
    name: Sleeping
    icon: mdi:sleep
  alarm_override_ingrid:
    name: Alarm Disabled
    icon: mdi:cancel
  alarm_workday_ingrid:
    name: Workdays Only
    icon: mdi:calendar-check

  sleep_state_guests:
    name: Sleeping
    icon: mdi:sleep
  guests_present:
    name: Hospitality
    icon: mdi:account-multiple-plus
  vacation_mode:
    name: Vacation
    icon: mdi:beach
  door_autolock:
    name: Auto lock
    icon: mdi:lock-reset

input_datetime:
  alarm_time_tor:
    name: Alarm Time
    has_date: false
    has_time: true
  alarm_time_lande:
    name: Alarm Time
    has_date: false
    has_time: true
  alarm_time_ingrid:
    name: Alarm Time
    has_date: false
    has_time: true

switch:
 platform: command_line
 switches:
   #Switch for Foscam Motion Detection
   foscam_motion:
     command_on: !secret foscam_command_on
     command_off: !secret foscam_command_off
     command_state: !secret foscam_command_state
     value_template: '{{ value == "1" }}'

notify:
  - name: mail
    platform: smtp
    sender: !secret notify_mail_sender
    sender_name: My Home Assistant
    recipient: !secret notify_mail_recipient
    server: !secret notify_mail_server
    port: 25
  - name: html5
    platform: html5
    gcm_api_key: !secret gcm_sender_key
    gcm_sender_id: !secret gcm_sender_id

shell_command:
  snapshot: !secret shell_command_snapshot


google_assistant:
  project_id: api-project-511361644410
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  agent_user_id: !secret google_assistant_agent_user_id
  api_key: !secret google_assistant_api_key
  expose_by_default: false
  entity_config:
    input_boolean.sleep_state_tor:
      name: tor magnus sleeping
      expose: true
      aliases:
      room: Master bedroom
    input_boolean.sleep_state_lande:
      name: lande sleeping
      expose: true
      aliases:
      room: Master bedroom
    input_boolean.sleep_state_ingrid:
      name: ingrid sleeping
      expose: true
      aliases:
      room: Ingrid bedroom
    light.bedside_lamp_dimmer_level:
      name: bedside lamp
      expose: true
      room: Master Bedroom
    light.bedroom_tv_backlight_level:
      name: tv backlight
      expose: true
      room: Master Bedroom
    switch.dressing_table_light_switch:
      name: dressing table lamp
      expose: true
      room: Master Bedroom
    light.kitchen_bench_ceiling_lights_level:
      name: kitchen bench light
      expose: true
      room: Kitchen
    light.kitchen_table_ceiling_lamp_level:
      name: kitchen table light
      expose: true
      room: Kitchen
    light.kitchen_hallway_ceiling_lights_level:
      name: kitchen hallway light
      expose: true
      room: Kitchen
    switch.dining_room_standing_lamp_switch:
      name: reading light
      expose: true
      room: Dining room
    switch.corner_standing_lamp_switch:
      name: corner light
      expose: true
      room: Dining room
    switch.cabinet_lights_switch:
      name: cabinet light
      expose: true
      room: Dining room
    switch.serving_table_lamp_switch:
      name: serving table light
      expose: true
      room: Dining room
    switch.side_table_light_switch:
      name: bookshelf light
      expose: true
      room: Dining room
    light.dining_room_rail_1_level:
      name: ceiling light
      expose: true
      room: Dining room
    light.dining_room_rail_2_level:
      name: office light
      expose: true
      room: Dining room
    light.tv_area_level:
      name: tv ceiling light
      expose: true
      room: TV Room
    light.sofa_area_level:
      name: sofa ceiling light
      expose: true
      room: TV Room
    light.hallway_area_level:
      name: hallway ceiling light
      expose: true
      room: TV Room

binary_sensor: !include binary-sensor.yaml
sensor: !include sensor.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
alert: !include alerts.yaml
