- platform: template
  fans:
    humidity_fan:
      friendly_name: "Humidity extraction fan"
      value_template: "{{ states('light.house_ventilation_dimmer_level') }}"
      speed_template: >-
        {% if states('light.house_ventilation_dimmer_level') == 'on' -%}
          {%- if state_attr('light.house_ventilation_dimmer_level', 'brightness') >= 1  and state_attr('light.house_ventilation_dimmer_level', 'brightness') < 86 -%}
            1
          {%- elif state_attr('light.house_ventilation_dimmer_level', 'brightness') >= 86  and state_attr('light.house_ventilation_dimmer_level', 'brightness') < 171 -%}
            2
          {%- elif state_attr('light.house_ventilation_dimmer_level', 'brightness') >= 171  and state_attr('light.house_ventilation_dimmer_level', 'brightness') < 256 -%}
            3
          {%- endif -%}
        {%- else -%}
          1
        {%- endif %}
      turn_on:
        service: light.turn_on
        entity_id: light.house_ventilation_dimmer_level
      turn_off:
        service: light.turn_off
        entity_id: light.house_ventilation_dimmer_level
      set_speed:
        service: light.turn_on
        entity_id: light.house_ventilation_dimmer_level
        data_template:
          brightness: >- 
            {% if speed == '1' -%}
              85
            {%- elif speed == '2' -%}
              170
            {%- elif speed == '3' -%}
              255
            {%- endif %}
      speeds:
        - '1'
        - '2'
        - '3'
