- platform: yr
  name: Weather +2H
  forecast: 2
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: fitbit
  clock_format: 24H
  unit_system: metric
  monitored_resources:
    - "activities/steps"
    - "activities/heart"
    - "body/weight"
    - "sleep/minutesAsleep"

- platform: template
  sensors:
    average_humidity:
      friendly_name: "Average house humidity"
      unit_of_measurement: "% avg"
      icon_template: mdi:water-percent
      value_template: >
        {% if states.sensor %}
          {% set totalvalue = states.sensor | selectattr("attributes.unit_of_measurement","equalto","%")|selectattr("attributes.icon","defined")|map(attribute='state')|map('float')|sum %}
          {% set totalcount = states.sensor | selectattr("attributes.unit_of_measurement","equalto","%")|selectattr("attributes.icon","defined")|list|count %}
          {% set totalaverage = totalvalue / totalcount %}
          {{totalaverage|round(1)}}
        {% else %}
          40
        {% endif %}

    divergence_humidity:
      friendly_name: "Divergence from average house humidity"
      unit_of_measurement: "% div"
      icon_template: mdi:water-percent
      value_template: >
          {% if states.sensor.average_humidity.state and states.sensor.family_bathroom_multisensor_relative_humidity.state and states.sensor.master_bathroom_multisensor_relative_humidity.state and states.sensor.laundry_multisensor_relative_humidity.state %}
            {% set average = states.sensor.average_humidity.state|float %}
            {% set family = states.sensor.family_bathroom_multisensor_relative_humidity.state|float - average %}
            {% set master = states.sensor.master_bathroom_multisensor_relative_humidity.state|float - average %}
            {% set laundry = (states.sensor.laundry_multisensor_relative_humidity.state|float - average) - 4 %}
            {{[family,master,laundry]|max|round(1)}}
          {% else %}
            0
          {% endif %}

    average_temperature:
      friendly_name: "Average house temperature"
      unit_of_measurement: "°C avg"
      icon_template: mdi:water-percent
      value_template: >
        {% if states.sensor %}
          {% set totalvalue = states.sensor | selectattr("attributes.unit_of_measurement","equalto","°C")|map(attribute='state')|map('float')|sum %}
          {% set totalcount = states.sensor | selectattr("attributes.unit_of_measurement","equalto","°C")|list|count %}
          {% set totalaverage = totalvalue / totalcount %}
          {{totalaverage|round(1)}}
        {% else %}
          20
        {% endif %}

    sunrise:
      friendly_name: "Sunrise at"
      icon_template: mdi:weather-sunset-up
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%H:%M") }}'
    sunset:
      friendly_name: "Sunset at"
      icon_template: mdi:weather-sunset-down
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%H:%M") }}'
    fitbit_steps:
      friendly_name: 'Steps'
      value_template: >
        {{ states.sensor.steps.state | replace(",","") }}
      unit_of_measurement: 'steps'
    fitbit_calories:
      friendly_name: 'Calories'
      value_template: >
        {{ states.sensor.calories.state | replace(",","") }}
      unit_of_measurement: 'calories'
    weight_loss:
      friendly_name: 'Weight Loss'
      value_template: "{{ '%.1f' | format(82.0 - (states.sensor.weight.state | float)) }}"
      unit_of_measurement: 'kg'
