- platform: yr
  name: Weather 
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - humidity
    - cloudiness

- platform: nordpool
  currency: 'NOK'
  region: 'Oslo'
  name: "Elspot kWh"

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: fitbit
  clock_format: 24H
  unit_system: metric
  monitored_resources:
    - "activities/steps"
    - "activities/heart"
    - "body/weight"
    - "sleep/minutesAsleep"

- platform: template
  sensors:
    electricity_price:
      friendly_name: "GE spot price kWh"
      entity_id: sensor.elspot_kwh
      icon_template: mdi:flash
      unit_of_measurement: "øre"
      value_template: '{{float(states.sensor.elspot_kwh.state) + 3.2}}'

    average_humidity:
      friendly_name: "Average house humidity"
      entity_id: sensor.family_bathroom_multisensor_relative_humidity, sensor.master_bathroom_multisensor_relative_humidity, sensor.laundry_multisensor_relative_humidity
      unit_of_measurement: "% avg"
      icon_template: mdi:water-percent
      value_template: >
        {% if states.sensor %}
          {% set totalvalue = states.sensor | selectattr("attributes.unit_of_measurement","equalto","%")|selectattr("attributes.icon","equalto","mdi:water-percent")|map(attribute='state')|map('float')|sum %}
          {% set totalcount = states.sensor | selectattr("attributes.unit_of_measurement","equalto","%")|selectattr("attributes.icon","equalto","mdi:water-percent")|list|count %}
          {% if totalcount > 0 %}
            {% set totalaverage = totalvalue / totalcount %}
          {% else %}
            {% set totalaverage = 40 %}
          {% endif %}
          {{totalaverage|round(1)}}
        {% else %}
          40
        {% endif %}

    divergence_humidity:
      friendly_name: "Divergence from average house humidity"
      entity_id: sensor.average_humidity, sensor.family_bathroom_multisensor_relative_humidity, sensor.master_bathroom_multisensor_relative_humidity, sensor.laundry_multisensor_relative_humidity
      unit_of_measurement: "% div"
      icon_template: mdi:water-percent
      value_template: >
          {% if states.sensor.average_humidity.state and states.sensor.family_bathroom_multisensor_relative_humidity.state and states.sensor.master_bathroom_multisensor_relative_humidity.state and states.sensor.laundry_multisensor_relative_humidity.state %}
            {% set average = states.sensor.average_humidity.state|float %}
            {% set family = states.sensor.family_bathroom_multisensor_relative_humidity.state|float - average %}
            {% set master = states.sensor.master_bathroom_multisensor_relative_humidity.state|float - average %}
            {% set laundry = (states.sensor.laundry_multisensor_relative_humidity.state|float - average) - 3 %}
            {{[family,master,laundry]|max|round(1)}}
          {% else %}
            0
          {% endif %}

    average_temperature:
      friendly_name: "Average house temperature"
      entity_id: sensor.entrance_hallway_motion_sensor_temperature, sensor.hallway_toilet_motion_sensor_temperature, sensor.laundry_multisensor_temperature, sensor.kitchen_table_motion_sensor_temperature, sensor.kitchen_island_motion_sensor_temperature, sensor.dining_room_stairs_motion_sensor_temperature, sensor.balcony_door_sensor_temperature, sensor.tv_area_motion_sensor_temperature, sensor.family_bathroom_multisensor_temperature, sensor.dressingroom_motion_sensor_temperature, sensor.master_bathroom_multisensor_temperature, sensor.training_room_motion_sensor_temperature
      unit_of_measurement: "°C avg"
      icon_template: mdi:water-percent
      value_template: >
        {% if states.sensor %}
          {% set totalvalue = states.sensor | selectattr("attributes.unit_of_measurement","equalto","°C") | selectattr("attributes.value_index","equalto",1) | map(attribute='state') | map('float') | sum %}
          {% set totalcount = states.sensor | selectattr("attributes.unit_of_measurement","equalto","°C") | selectattr("attributes.value_index","equalto",1) | list | count %}
          {% if totalcount > 0 %}
            {% set totalaverage = totalvalue / totalcount %}
          {% else %}
            {% set totalaverage = 20 %}
          {% endif %}
          {{totalaverage|round(1)}}
        {% else %}
          20
        {% endif %}

    sunrise:
      friendly_name: "Sunrise at"
      entity_id: sun.sun
      icon_template: mdi:weather-sunset-up
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%H:%M") }}'
    sunset:
      friendly_name: "Sunset at"
      entity_id: sun.sun
      icon_template: mdi:weather-sunset-down
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%H:%M") }}'
    fitbit_steps:
      friendly_name: 'Steps'
      value_template: >
        {{ states.sensor.steps.state | replace(',','') }}
      unit_of_measurement: 'steps'
    fitbit_calories:
      friendly_name: 'Calories'
      value_template: >
        {{ states.sensor.calories.state | replace(',','') }}
      unit_of_measurement: 'calories'
    weight_loss:
      friendly_name: 'Weight Loss'
      value_template: "{{ '%.1f' | format(82.0 - (states.sensor.weight.state | float)) }}"
      unit_of_measurement: 'kg'
