- id: '1'
  alias: 'message'
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
     action: 'blah'
  action:
    - service: notify.html5_tor_magnus_phone
      data:
        message: 'Someone at door'
        data:
          actions:
            - action: 'open_door'
              title: 'Open door'

- id: '58'
  alias: 'HTML5 push notification action button clicked'
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
     action: open_door
  action:
    - service: notify.html5_tor_magnus_phone
      data:
        message: 'Door opened'


- id: '2'
  alias: 'Picture on open front door'
  trigger:
    platform: state
    entity_id: lock.front_door_lock_locked
    to: unlocked
  action:
    - service: shell_command.snapshot
      data:
        filename: snapshot.jpg
    - delay:
        seconds: 1
    - service: notify.html5_tor_magnus_phone
      data_template:
        title: 'Door opened'
        message: 'The front door was opened'
        data:
          image: !secret doorway_snapshot
    - service: notify.mail
      data:
        title: 'Door opened'
        message: 'The front door was opened'
        data:
          images:
            - /config/www/snapshot.jpg
#- id: '14'
#  alias: 'Starting Home Assistant'
#  trigger:
#    platform: homeassistant
#    event: start
#  condition:
#    condition: state
#    entity_id: input_select.home_state
#    state: 'Home'
#  action:
#    - service: switch.turn_on
#      entity_id: switch.fluxed_tv_backlight
