- id: '1'
  alias: 'message'
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
     action: 'blah'
  action:
    - service: notify.html5_tor_magnus_pixel
      data:
        message: 'Someone at door'
        data:
          actions:
            - action: 'open_door'
              title: 'Open door'

- id: '58'
  alias: 'HTML5 push notification action button clicked'
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
     action: open_door
  action:
    - service: notify.html5
      data:
        message: 'Door opened'
        data:
          tag: 'test-notification'


- id: '2'
  alias: 'Picture on open front door'
  trigger:
    platform: state
    entity_id: lock.front_door_lock_locked
    to: unlocked
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.dining_room
        volume_level: 0.55
    - service: script.turn_on
      entity_id: script.say_sonos
      data:
        variables:
          where: 'dining_room'
          what: 'The front door is open.'
    - service: shell_command.snapshot
      data:
        filename: snapshot.jpg
    - delay:
        seconds: 2
    - service: notify.html5
      data_template:
        title: 'Door opened'
        message: 'The front door was opened'
        data:
          image: !secret doorway_snapshot
          renotify: 1
          tag: 'door-open-notification'
#    - service: notify.mail
#      data:
#        title: 'Door opened'
#        message: 'The front door was opened'
#        data:
#          images:
#            - /config/www/snapshot.jpg

- id: '86'
  alias: 'Enable autolock'
  trigger:
    platform: state
    entity_id: input_boolean.door_autolock
    to: 'on'
  action:
    - service: zwave.set_config_parameter
      data:
        node_id: 47
        parameter: 1
        value: 'Disable Away, Auto Lock'

- id: '87'
  alias: 'Disable autolock'
  trigger:
    platform: state
    entity_id: input_boolean.door_autolock
    to: 'off'
  action:
    - service: zwave.set_config_parameter
      data:
        node_id: 47
        parameter: 1
        value: 'Disable Away, Manual Lock'

- id: '88'
  alias: 'Set evening autolock'
  trigger:
    platform: time
    at: '19:45:00'
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.door_autolock

#- id: '14'
#  alias: 'Starting Home Assistant'
#  trigger:
#    platform: homeassistant
#    event: start
#  condition:
#    condition: state
#    entity_id: input_select.home_state
#    state: 'Home'
#  action:
#    - service: switch.turn_on
#      entity_id: switch.fluxed_tv_backlight
